export const ListingDummies = [
  {
    id: 1,
    image: "/svgs/common/room-img.svg",
    price: "주 / 100.0$",
    status: "거래 중",
    area: "nn m²",
    floor: "전체 n층",
    type: "매물 종류",
    options: "빌 포함",
    distance: "역까지 Nkm",
    location: "chatswood",
    timeAgo: "N분 전",
    likes: 234,
  },
  {
    id: 2,
    image: "/svgs/common/room-img.svg",
    price: "주 / 100.0$",
    status: "거래 중",
    area: "nn m²",
    floor: "전체 n층",
    type: "매물 종류",
    options: "빌 포함",
    distance: "역까지 Nkm",
    location: "chatswood",
    timeAgo: "N분 전",
    likes: 234,
  },
  {
    id: 3,
    image: "/svgs/common/room-img.svg",
    price: "주 / 100.0$",
    status: "거래 중",
    area: "nn m²",
    floor: "전체 n층",
    type: "매물 종류",
    options: "빌 포함",
    distance: "역까지 Nkm",
    location: "chatswood",
    timeAgo: "N분 전",
    likes: 234,
  },
];
